#
# This sample yaml configuration file contains two stages and three jobs.
# This configuration uses GitLab's `only`, `when`, and `except` configuration
# options to create a pipeline that will create the `pulumi-preview` job in the pipeline,
# for all branches except the master.
# Only for master branch merges, the main `pulumi` job is executed automatically.
image:
  name: pulumi/pulumi:3.150.0
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - build
  - infrastructure-update

pulumi:
  stage: infrastructure-update
  script:
    - npm ci
    - pulumi stack select bjoern_urban_5/pulumi-infra/dev
    - pulumi update --skip-preview
  # Create an artifact archive with just the pulumi log file,
  # which is created using console-redirection in run-pulumi.sh.
  artifacts:
    paths:
      - pulumi-log.txt
    # This is just a sample of how artifacts can be expired (removed) automatically in GitLab.
    # You may choose to not set this at all based on your organization's or team's preference.
    expire_in: 1 week
  # This job should only be created if the pipeline is created for the master branch.
  only:
    - master

pulumi-preview:
  stage: infrastructure-update
  script:
    - npm ci
    - pulumi stack select bjoern_urban_5/pulumi-infra/dev
    - pulumi preview
  only:
    - merge_requests
