#
# This sample yaml configuration file contains two stages and three jobs.
# This configuration uses GitLab's `only`, `when`, and `except` configuration
# options to create a pipeline that will create the `pulumi-preview` job in the pipeline,
# for all branches except the master.
# Only for master branch merges, the main `pulumi` job is executed automatically.
image:
  name: pulumi/pulumi:3.35.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - build-directus-app
  - build-directus-container
  - build
  - infrastructure-update

build-directus-app:
  stage: build-directus-app
  variables:
    NODE_OPTIONS: --max_old_space_size=4096
    DIRECTUS_VERSION: "v9.14.5"
  image: node:16
  script:
    - git clone --depth 1 --branch $DIRECTUS_VERSION https://github.com/directus/directus.git && cd directus
    - npm install -g pnpm
    - pnpm -r install
    - pnpm -r build
  artifacts:
    untracked: true
    paths:
      - directus/
    expire_in: 1 hour

build-directus-container:
  stage: build-directus-container
  dependencies:
    - build-directus-app
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    NODE_VERSION: "16"
  script:
    - ls
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cd directus && /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/directus/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

pulumi:
  stage: infrastructure-update
  script:
    - npm ci
    - pulumi stack select bjoern_urban_5/pulumi-infra/dev
    - pulumi update --skip-preview
  # Create an artifact archive with just the pulumi log file,
  # which is created using console-redirection in run-pulumi.sh.
  artifacts:
    paths:
      - pulumi-log.txt
    # This is just a sample of how artifacts can be expired (removed) automatically in GitLab.
    # You may choose to not set this at all based on your organization's or team's preference.
    expire_in: 1 week
  # This job should only be created if the pipeline is created for the master branch.
  only:
    - master

pulumi-preview:
  stage: infrastructure-update
  script:
    - npm ci
    - pulumi stack select bjoern_urban_5/pulumi-infra/dev
    - pulumi preview
  only:
    - merge_requests
