name: Deploy Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CI: true

jobs:
  pulumi-deploy-dev:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm install
      - name: Decode kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >  $HOME/.kube/config
          cat $HOME/.kube/config
        shell: bash
      - name: Set Version in pulumi config
        uses: pulumi/actions@v6
        with:
          command: config set version $versionTag
          stack-name: openstack
          work-dir: flux-operator
      - name: Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: openstack
          work-dir: flux-operator
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      versionTag: ${{ github.head_ref || github.ref_name }}
  pulumi-deploy-prod:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: npm install
      - name: Decode kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >  $HOME/.kube/config
          cat $HOME/.kube/config
        shell: bash
      - name: Set Version in pulumi config
        uses: pulumi/actions@v6
        with:
          command: config set version $versionTag
          stack-name: hetzner
          work-dir: flux-operator
      - name: Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: hetzner
          work-dir: flux-operator
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      versionTag: ${{ github.head_ref || github.ref_name }}
