name: Deploy Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CI: true

jobs:
  pulumi-deploy-dev:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - run: npm install
      - name: Decode kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >  $HOME/.kube/config
          cat $HOME/.kube/config
        shell: bash
      - name: Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: openstack
          work-dir: flux-operator
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      versionTag: ${{ github.head_ref || github.ref_name }}
  pulumi-deploy-prod:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - run: npm install
      - name: setup kubectl
        uses: actions-hub/kubectl@v1.36.3
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Decode kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >  $HOME/.kube/config
          cat $HOME/.kube/config
        shell: bash
      - name: Get current Version in pulumi config
        run: |
          echo "PREVIOUS_VERSION=kubectl get stacks -n flux-system l1 -o jsonpath='{.spec.branch}' | awk -F'/' '{print $NF}'" >> $GITHUB_ENV
      - name: Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: hetzner
          work-dir: flux-operator
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      versionTag: ${{ github.head_ref || github.ref_name }}
