name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fail-fast: false
        workdir: [ l0, l1, l2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '19.9.0'
      - run: npm install
        working-directory: ${{ matrix.workdir }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: ${{ matrix.workdir }}
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
