name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: [ l0, l1, l2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: 19.9.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
        working-directory: ${{ matrix.workdir }}
      - uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: ${{ matrix.workdir }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
