name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
        with:
          node-version-file: package.json
      - run: npm install
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: hetzner # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
