name: Pulumi
on:
  push:
      branches:
        - "master"
        - "development"
        - "renovate/*"

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workdir: [ l1, l2 ]
        stack: [hetzner]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '19.9.0'
      - uses: actions-hub/kubectl@v1.31.2
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      - run: npm install
        working-directory: ${{ matrix.workdir }}
      - uses: pulumi/actions@v6
        with:
          command: preview
          work-dir: ${{ matrix.workdir }}
          stack-name: ${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
